<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::table('users')->insert([
            [
                'id' => \App\Enums\UserType::superadmin,
                'name' => 'superadmin',
                'email' => 'superadmin@gmail.com',
                'password' => bcrypt('1qaz!QAZ'),
                'api_token' => \Illuminate\Support\Str::random(80),
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => now(),
                'fname' => \Ybazli\Faker\Facades\Faker::firstName(),
                'lname' => \Ybazli\Faker\Facades\Faker::lastName(),
                'factory' => \Ybazli\Faker\Facades\Faker::word(),
                'province' => \Ybazli\Faker\Facades\Faker::state(),
                'city' => \Ybazli\Faker\Facades\Faker::city(),
                'address1' => \Ybazli\Faker\Facades\Faker::address(),
                'address2' => \Ybazli\Faker\Facades\Faker::address(),
                'phone' => \Ybazli\Faker\Facades\Faker::word(),
                'pre_phone' => rand(111,999),
                'country' => \Ybazli\Faker\Facades\Faker::word(),
                'desc' => \Ybazli\Faker\Facades\Faker::paragraph(),
            ],
            [
                'id' => \App\Enums\UserType::owner,
                'name' => 'owner',
                'email' => 'owner@gmail.com',
                'password' => bcrypt('1qaz!QAZ'),
                'api_token' => \Illuminate\Support\Str::random(80),
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => now(),
                'fname' => \Ybazli\Faker\Facades\Faker::firstName(),
                'lname' => \Ybazli\Faker\Facades\Faker::lastName(),
                'factory' => \Ybazli\Faker\Facades\Faker::word(),
                'province' => \Ybazli\Faker\Facades\Faker::state(),
                'city' => \Ybazli\Faker\Facades\Faker::city(),
                'address1' => \Ybazli\Faker\Facades\Faker::address(),
                'address2' => \Ybazli\Faker\Facades\Faker::address(),
                'phone' => \Ybazli\Faker\Facades\Faker::word(),
                'pre_phone' => rand(111,999),
                'country' => \Ybazli\Faker\Facades\Faker::word(),
                'desc' => \Ybazli\Faker\Facades\Faker::paragraph(),
            ],
            [
                'id' => \App\Enums\UserType::financial,
                'name' => 'financial',
                'email' => 'financial@gmail.com',
                'password' => bcrypt('1qaz!QAZ'),
                'api_token' => \Illuminate\Support\Str::random(80),
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => now(),
                'fname' => \Ybazli\Faker\Facades\Faker::firstName(),
                'lname' => \Ybazli\Faker\Facades\Faker::lastName(),
                'factory' => \Ybazli\Faker\Facades\Faker::word(),
                'province' => \Ybazli\Faker\Facades\Faker::state(),
                'city' => \Ybazli\Faker\Facades\Faker::city(),
                'address1' => \Ybazli\Faker\Facades\Faker::address(),
                'address2' => \Ybazli\Faker\Facades\Faker::address(),
                'phone' => \Ybazli\Faker\Facades\Faker::word(),
                'pre_phone' => rand(111,999),
                'country' => \Ybazli\Faker\Facades\Faker::word(),
                'desc' => \Ybazli\Faker\Facades\Faker::paragraph(),
            ],
            [
                'id' => \App\Enums\UserType::protection,
                'name' => 'protection',
                'email' => 'protection@gmail.com',
                'password' => bcrypt('1qaz!QAZ'),
                'api_token' => \Illuminate\Support\Str::random(80),
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => now(),
                'fname' => \Ybazli\Faker\Facades\Faker::firstName(),
                'lname' => \Ybazli\Faker\Facades\Faker::lastName(),
                'factory' => \Ybazli\Faker\Facades\Faker::word(),
                'province' => \Ybazli\Faker\Facades\Faker::state(),
                'city' => \Ybazli\Faker\Facades\Faker::city(),
                'address1' => \Ybazli\Faker\Facades\Faker::address(),
                'address2' => \Ybazli\Faker\Facades\Faker::address(),
                'phone' => \Ybazli\Faker\Facades\Faker::word(),
                'pre_phone' => rand(111,999),
                'country' => \Ybazli\Faker\Facades\Faker::word(),
                'desc' => \Ybazli\Faker\Facades\Faker::paragraph(),
            ],
            [
                'id' => \App\Enums\UserType::successor,
                'name' => 'successor',
                'email' => 'successor@gmail.com',
                'password' => bcrypt('1qaz!QAZ'),
                'api_token' => \Illuminate\Support\Str::random(80),
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => now(),
                'fname' => \Ybazli\Faker\Facades\Faker::firstName(),
                'lname' => \Ybazli\Faker\Facades\Faker::lastName(),
                'factory' => \Ybazli\Faker\Facades\Faker::word(),
                'province' => \Ybazli\Faker\Facades\Faker::state(),
                'city' => \Ybazli\Faker\Facades\Faker::city(),
                'address1' => \Ybazli\Faker\Facades\Faker::address(),
                'address2' => \Ybazli\Faker\Facades\Faker::address(),
                'phone' => \Ybazli\Faker\Facades\Faker::word(),
                'pre_phone' => rand(111,999),
                'country' => \Ybazli\Faker\Facades\Faker::word(),
                'desc' => \Ybazli\Faker\Facades\Faker::paragraph(),
            ],
            [
                'id' => \App\Enums\UserType::master,
                'name' => 'master',
                'email' => 'master@gmail.com',
                'password' => bcrypt('1qaz!QAZ'),
                'api_token' => \Illuminate\Support\Str::random(80),
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => now(),
                'fname' => \Ybazli\Faker\Facades\Faker::firstName(),
                'lname' => \Ybazli\Faker\Facades\Faker::lastName(),
                'factory' => \Ybazli\Faker\Facades\Faker::word(),
                'province' => \Ybazli\Faker\Facades\Faker::state(),
                'city' => \Ybazli\Faker\Facades\Faker::city(),
                'address1' => \Ybazli\Faker\Facades\Faker::address(),
                'address2' => \Ybazli\Faker\Facades\Faker::address(),
                'phone' => \Ybazli\Faker\Facades\Faker::word(),
                'pre_phone' => rand(111,999),
                'country' => \Ybazli\Faker\Facades\Faker::word(),
                'desc' => \Ybazli\Faker\Facades\Faker::paragraph(),
            ],
            [
                'id' => \App\Enums\UserType::support,
                'name' => 'support',
                'email' => 'support@gmail.com',
                'password' => bcrypt('1qaz!QAZ'),
                'api_token' => \Illuminate\Support\Str::random(80),
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => now(),
                'fname' => \Ybazli\Faker\Facades\Faker::firstName(),
                'lname' => \Ybazli\Faker\Facades\Faker::lastName(),
                'factory' => \Ybazli\Faker\Facades\Faker::word(),
                'province' => \Ybazli\Faker\Facades\Faker::state(),
                'city' => \Ybazli\Faker\Facades\Faker::city(),
                'address1' => \Ybazli\Faker\Facades\Faker::address(),
                'address2' => \Ybazli\Faker\Facades\Faker::address(),
                'phone' => \Ybazli\Faker\Facades\Faker::word(),
                'pre_phone' => rand(111,999),
                'country' => \Ybazli\Faker\Facades\Faker::word(),
                'desc' => \Ybazli\Faker\Facades\Faker::paragraph(),
            ],
            [
                'id' => \App\Enums\UserType::supplier,
                'name' => 'supplier',
                'email' => 'supplier@gmail.com',
                'password' => bcrypt('1qaz!QAZ'),
                'api_token' => \Illuminate\Support\Str::random(80),
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => now(),
                'fname' => \Ybazli\Faker\Facades\Faker::firstName(),
                'lname' => \Ybazli\Faker\Facades\Faker::lastName(),
                'factory' => \Ybazli\Faker\Facades\Faker::word(),
                'province' => \Ybazli\Faker\Facades\Faker::state(),
                'city' => \Ybazli\Faker\Facades\Faker::city(),
                'address1' => \Ybazli\Faker\Facades\Faker::address(),
                'address2' => \Ybazli\Faker\Facades\Faker::address(),
                'phone' => \Ybazli\Faker\Facades\Faker::word(),
                'pre_phone' => rand(111,999),
                'country' => \Ybazli\Faker\Facades\Faker::word(),
                'desc' => \Ybazli\Faker\Facades\Faker::paragraph(),
            ],
        ]);
    }
}
